[package]

name = "rusteroids"
version = "1.0.0"
authors = [ "benbrunton@hotmail.com" ]

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies]
rand = "0.7.0"
gl = "0.6.0"
glfw = "0.30.0"
